language: node_js

sudo: flase 
dist: trusty

node_js:
  - 8

cache:
  - $HOME/.npm

branches:
  only:
    - master

before_install:
  - export TZ='Asia/Shanghai'

install:
  - npm install gitbook-cli -g
  - gitbook install

script:
  - gitbook build .
  - chmod u+x .travis/deploy.sh

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
