language: node_js

sudo: required 
dist: trusty

node_js:
  - "lts/*"

cache:
  apt: true
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install gitbook-cli -g
  - gitbook install

script:
  - gitbook build .
  - chmod u+x .travis/deploy.sh

deploy:
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    branch: master
